// Global public ingress: Azure Front Door Premium with WAF, reaching each region's App Service over Private Link.

@description('Front Door profile name.')
@minLength(1)
@maxLength(90)
param profileName string

@description('Front Door endpoint name. Azure appends a hash to form <name>-<hash>.z01.azurefd.net.')
@minLength(1)
@maxLength(46)
param endpointName string

@description('WAF policy name. Letters and digits only, starting with a letter.')
@minLength(1)
@maxLength(128)
param wafPolicyName string

@description('Origins in failover order: the first entry is priority 1 (active), the next priority 2 (standby). Each entry: { name, appServiceId, hostName, location }.')
@minLength(1)
@maxLength(5)
param origins array

@description('Relative path Front Door probes on every origin (the App Service health check path).')
param healthProbePath string = '/'

@description('Custom domain served by the endpoint, for example app.example.com. Empty serves only the azurefd.net hostname.')
param customDomainHostName string = ''

@description('Requests per minute from one client IP before the WAF blocks it.')
@minValue(100)
@maxValue(100000)
param rateLimitThresholdPerMinute int = 1000

@description('ISO 3166-1 alpha-2 country codes allowed to reach the app. Empty disables geo-filtering.')
param allowedCountryCodes array = []

@description('Log Analytics workspace resource ID for access, health probe and WAF logs.')
param logAnalyticsWorkspaceId string

@description('Apply CanNotDelete locks to the profile and the WAF policy.')
param enableDeleteLock bool = false

// The request message Front Door attaches to each private endpoint connection; the approval script matches on it.
var privateLinkRequestMessage = 'defenstack-frontdoor'
var hasCustomDomain = !empty(customDomainHostName)
var customDomainName = replace(customDomainHostName, '.', '-')

var rateLimitRule = {
  name: 'RateLimitPerClientIp'
  priority: 100
  enabledState: 'Enabled'
  ruleType: 'RateLimitRule'
  rateLimitDurationInMinutes: 1
  rateLimitThreshold: rateLimitThresholdPerMinute
  matchConditions: [
    {
      matchVariable: 'RemoteAddr'
      operator: 'IPMatch'
      negateCondition: false
      matchValue: [
        '0.0.0.0/0'
        '::/0'
      ]
    }
  ]
  action: 'Block'
}
var geoFilterRules = empty(allowedCountryCodes) ? [] : [
  {
    name: 'BlockOutsideAllowedCountries'
    priority: 200
    enabledState: 'Enabled'
    ruleType: 'MatchRule'
    matchConditions: [
      {
        matchVariable: 'SocketAddr'
        operator: 'GeoMatch'
        negateCondition: true
        matchValue: allowedCountryCodes
      }
    ]
    action: 'Block'
  }
]

resource profile 'Microsoft.Cdn/profiles@2024-09-01' = {
  name: profileName
  location: 'global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  // Managed identity for future Key Vault certificate access (customer-managed TLS); managed certificates do not use it.
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    originResponseTimeoutSeconds: 60
  }
}

resource endpoint 'Microsoft.Cdn/profiles/afdEndpoints@2024-09-01' = {
  parent: profile
  name: endpointName
  location: 'global'
  properties: {
    enabledState: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
  }
}

// Prevention mode in every environment: Microsoft Default Rule Set 2.1, Bot Manager 1.1, and a per-IP rate limit.
resource wafPolicy 'Microsoft.Network/FrontDoorWebApplicationFirewallPolicies@2024-02-01' = {
  name: wafPolicyName
  location: 'Global'
  sku: {
    name: 'Premium_AzureFrontDoor'
  }
  properties: {
    policySettings: {
      enabledState: 'Enabled'
      mode: 'Prevention'
      requestBodyCheck: 'Enabled'
    }
    customRules: {
      rules: concat([
        rateLimitRule
      ], geoFilterRules)
    }
    managedRules: {
      managedRuleSets: [
        {
          ruleSetType: 'Microsoft_DefaultRuleSet'
          ruleSetVersion: '2.1'
          ruleSetAction: 'Block'
        }
        {
          ruleSetType: 'Microsoft_BotManagerRuleSet'
          ruleSetVersion: '1.1'
        }
      ]
    }
  }
}

resource originGroup 'Microsoft.Cdn/profiles/originGroups@2024-09-01' = {
  parent: profile
  name: 'app'
  properties: {
    loadBalancingSettings: {
      sampleSize: 4
      successfulSamplesRequired: 3
      additionalLatencyInMilliseconds: 50
    }
    healthProbeSettings: {
      probePath: healthProbePath
      probeRequestType: 'HEAD'
      probeProtocol: 'Https'
      probeIntervalInSeconds: 30
    }
    sessionAffinityState: 'Disabled'
  }
}

// Each origin is reached only over Private Link; App Service public network access stays disabled.
resource appOrigins 'Microsoft.Cdn/profiles/originGroups/origins@2024-09-01' = [for (origin, i) in origins: {
  parent: originGroup
  name: origin.name
  properties: {
    hostName: origin.hostName
    originHostHeader: origin.hostName
    httpPort: 80
    httpsPort: 443
    priority: i + 1
    weight: 1000
    enabledState: 'Enabled'
    enforceCertificateNameCheck: true
    sharedPrivateLinkResource: {
      privateLink: {
        id: origin.appServiceId
      }
      groupId: 'sites'
      privateLinkLocation: origin.location
      requestMessage: privateLinkRequestMessage
    }
  }
}]

// Front Door-managed certificate; the domain is validated with a TXT record at the external DNS host (runbook 04).
resource customDomain 'Microsoft.Cdn/profiles/customDomains@2024-09-01' = if (hasCustomDomain) {
  parent: profile
  name: hasCustomDomain ? customDomainName : 'unused'
  properties: {
    hostName: customDomainHostName
    tlsSettings: {
      certificateType: 'ManagedCertificate'
      minimumTlsVersion: 'TLS12'
    }
  }
}

resource route 'Microsoft.Cdn/profiles/afdEndpoints/routes@2024-09-01' = {
  parent: endpoint
  name: 'app'
  properties: {
    originGroup: {
      id: originGroup.id
    }
    customDomains: hasCustomDomain ? [
      {
        id: customDomain.id
      }
    ] : []
    supportedProtocols: [
      'Http'
      'Https'
    ]
    patternsToMatch: [
      '/*'
    ]
    forwardingProtocol: 'HttpsOnly'
    httpsRedirect: 'Enabled'
    linkToDefaultDomain: 'Enabled'
    enabledState: 'Enabled'
  }
  // A route needs at least one origin in its group.
  dependsOn: [
    appOrigins
  ]
}

resource securityPolicy 'Microsoft.Cdn/profiles/securityPolicies@2024-09-01' = {
  parent: profile
  name: 'waf'
  properties: {
    parameters: {
      type: 'WebApplicationFirewall'
      wafPolicy: {
        id: wafPolicy.id
      }
      associations: [
        {
          domains: concat([
            {
              id: endpoint.id
            }
          ], hasCustomDomain ? [
            {
              id: customDomain.id
            }
          ] : [])
          patternsToMatch: [
            '/*'
          ]
        }
      ]
    }
  }
}

// Access, health probe and WAF logs in the central workspace.
resource profileDiagnostics 'Microsoft.Insights/diagnosticSettings@2021-05-01-preview' = {
  scope: profile
  name: 'frontdoor-diagnostics'
  properties: {
    workspaceId: logAnalyticsWorkspaceId
    logs: [
      {
        categoryGroup: 'allLogs'
        enabled: true
      }
    ]
    metrics: [
      {
        category: 'AllMetrics'
        enabled: true
      }
    ]
  }
}

resource profileLock 'Microsoft.Authorization/locks@2020-05-01' = if (enableDeleteLock) {
  scope: profile
  name: '${profileName}-lck'
  properties: {
    level: 'CanNotDelete'
  }
}

resource wafPolicyLock 'Microsoft.Authorization/locks@2020-05-01' = if (enableDeleteLock) {
  scope: wafPolicy
  name: '${wafPolicyName}-lck'
  properties: {
    level: 'CanNotDelete'
  }
}

output profileName string = profile.name
output endpointHostName string = endpoint.properties.hostName
output frontDoorId string = profile.properties.frontDoorId
output customDomainValidationToken string = hasCustomDomain ? customDomain!.properties.validationProperties.validationToken : ''
output privateLinkRequestMessage string = privateLinkRequestMessage
